#!/bin/bash
# vim: ft=sh

# Python virtualenv layout using uv
# From: https://github.com/direnv/direnv/wiki/Python#uv
layout_uv() {
    if [[ -d ".venv" ]]; then
        VIRTUAL_ENV="$(pwd)/.venv"
    fi

    if [[ -z $VIRTUAL_ENV || ! -d $VIRTUAL_ENV ]]; then
        log_status "No virtual environment exists. Executing \`uv venv\` to create one."
        # This differs from the wiki version
        # --quiet to be not noisy, and --seed to add pip and maybe others
        uv venv --quiet --seed
        VIRTUAL_ENV="$(pwd)/.venv"
    fi

    PATH_add "$VIRTUAL_ENV/bin"
    export UV_ACTIVE=1  # or VENV_ACTIVE=1
    export VIRTUAL_ENV
}
